### ISSUE TITLE
lightbulb only on quick fixes?

### ISSUE THREAD

**Issue by oblitum** [xiyaowong/coc-lightbulb-#1]
Hi, thx for nice extension. Is it possible to provide an option to control on which kind of code action it should be displayed? Specifically I'd only find it useful if I could have it only enabled for quick fixes of actual code bugs, because for some servers that provide too many code actions, this lightbulb is always present, which reduces how useful it might be.

**Comment by oblitum** [comment]
Ops, I'm not sure why there's two repositories, I should have opened this in the other one instead? Not sure.

**Comment by xiyaowong** [comment]
> Hi, thx for nice extension. Is it possible to provide an option to control on which kind of code action it should be displayed? Specifically I'd only find it useful if I could have it only enabled for quick fixes of actual code bugs, because for some servers that provide too many code actions, this lightbulb is always present, which reduces how useful it might be.

I will add this option

**Comment by xiyaowong** [comment]
> Ops, I'm not sure why there's two repositories, I should have opened this in the other one instead? Not sure.

There is no need. Because I believe that everyone would prefer to use this repo because it is more compatible, simpler and less costly like coc butlin features

**Comment by oblitum** [comment]
Ah okay, now I got what happened, yeah, this one is much simpler for coc users.

**Comment by xiyaowong** [comment]
see setting `lightbulb.only`

**Comment by oblitum** [comment]
Thanks, nice!

**Comment by oblitum** [comment]
At the moment I didn't manage it to work. Gonna debug what's going on in the `string[]` to `CodeActionKind[]` conversion.

**Comment by oblitum** [comment]
Nevermind, figured out I should used lowercase for action names.
